name: CI

on:
  push:
  pull_request:

jobs:
  build-and-smoke:
    name: Build & Smoke (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]  # macOS-14 = Apple Silicon runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Swift 6.2
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.2"

      - name: Install ncurses (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libncursesw6 libncursesw6-dev

      - name: Install ncurses (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install ncurses
          # Symlinks pour harmoniser les chemins attendus par Package.swift (Intel-style) sur Apple Silicon
          PREFIX="$(brew --prefix ncurses)"
          sudo mkdir -p /usr/local/opt/ncurses/include /usr/local/opt/ncurses/lib
          sudo ln -sfn "$PREFIX/include" /usr/local/opt/ncurses/include
          sudo ln -sfn "$PREFIX/lib"     /usr/local/opt/ncurses/lib
          # Symlink headers directement visibles via publicHeadersPath
          ln -sfn "$PREFIX/include/ncursesw" Sources/CNcurses/include/ncursesw

      - name: Swift build (debug)
        env:
          TERM: xterm-256color
        run: swift build -v

      - name: Run NewtermSmoke (pseudo-TTY)
        env:
          TERM: xterm-256color
        run: |
          # 'script' fournit un pseudo-TTY pour éviter les surprises avec newterm()
          script -q /dev/null swift run NewtermSmoke

